name: MSFT Stock

on:
  push:
    branches:
    - msft-stock
  schedule:
  - cron: '5 * * * *'

jobs:
  generate:
    name: Generate Stock Chart
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: msft-stock
    - uses: actions/setup-node@v1
    - run: yarn --frozen-lockfile
    - run: yarn test
    - id: run
      run: |
        echo '::set-output name=chart::'
        yarn start
    outputs:
      chart: ${{ steps.run.outputs.chart }}

  update:
    needs: generate
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - run: |
        cat <<'EOF' | tee README.md
        # MSFT Stock

        ```
        {{needs.generate.outputs.chart}}
        ```
        EOF
        git add README.md
        git commit -m 'Update README.md'
        git push origin master
