name: README.md

on:
  push:
  schedule:
  - cron: '0 * * * *'

jobs:
  msft-stock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: msft-stock
      uses: ./.github/actions/msft-stock
    outputs:
      chart: ${{ steps.msft-stock.outputs.chart }}

  github-stars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: github-stars
      uses: ./.github/actions/github-stars
      env:
        TOKEN: ${{ github.token }}
    outputs:
      markdown: ${{ steps.github-stars.outputs.markdown }}

  update:
    needs:
    - msft-stock
    - github-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cat <<'EOF' | tee README.md
        ![README.md](https://github.com/Gerhut/Gerhut/workflows/README.md/badge.svg)
        ![visitors](https://visitors.vercel.app/Gerhut/Gerhut?token=8cf69d1f6813d272ef062726b6070c9be4ff72038cfe5a7ded7384a8da65d866)

        ## MSFT Stock

        ```
        ${{ needs.msft-stock.outputs.chart }}
        ```

        ## Recently Starred Repos

        ${{ needs.github-stars.outputs.markdown }}
        EOF
    - id: diff
      run: git diff --exit-code
      continue-on-error: true
    - if: ${{ steps.diff.outcome == 'failure' }}
      run: |
        git add .
        git config --local user.name "GitHub Action"
        git config --local user.email action@github.com
        git commit --message 'Update'
        git push
