name: Generate README.md

on:
  push:
    branches:
    - msft-stock
  schedule:
  - cron: '0 * * * *'

jobs:
  msft-stock:
    name: MSFT Stock
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: msft-stock
    - uses: actions/setup-node@v1
    - run: yarn --frozen-lockfile
    - id: run
      run: |
        printf '::set-output name=chart::'
        yarn --silent start | npx encode-uri-component
    outputs:
      chart: ${{ steps.run.outputs.chart }}

  update:
    needs:
    - msft-stock
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - run: |
        cat <<'EOF' | tee README.md
        ![README](https://github.com/Gerhut/Gerhut/workflows/README/badge.svg)
        ![visitors](https://visitor-badge.glitch.me/badge?page_id=Gerhut.Gerhut)

        ```
        # MSFT Stock #

        ${{ needs.msft-stock.outputs.chart }}
        ```
        EOF
    - id: changed
      run: git diff --exit-code
      continue-on-error: true
    - if: ${{ steps.changed.outcome == 'failure' }}
      run: |
        git add README.md
        git config --local user.name "GitHub Action"
        git config --local user.email action@github.com
        git commit --message 'Update README.md'
    - if: ${{ steps.changed.outcome == 'failure' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
